VidlyMVC5/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace VidlyMVC5.Models
{
    public class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
}
}

VidlyMVC5/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace VidlyMVC5.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

VidlyMVC5/Models/MyDbContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace VidlyMVC5.Models
{

    public class MyDbContext : DbContext
    {
        public MyDbContext()
        {
        }
    }

}

VidlyMVC5/ViewModels/Del_CustomersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using VidlyMVC5.Models;

namespace VidlyMVC5.ViewModels
{
    public class Del_CustomersViewModel
    {
        public List<Customer> Customers { get; set; }
    }
}

VidlyMVC5/ViewModels/MovieCustomersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using VidlyMVC5.Models;

namespace VidlyMVC5.ViewModels
{
    public class MovieCustomersViewModel
    {
        public Movie Movie { get; set; }
        public List<Customer> Customers { get; set; }
    }
}

VidlyMVC5/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VidlyMVC5.Models;
using System.Data.Entity;


namespace VidlyMVC5.Controllers
{
    public class CustomersController : Controller
    {
        //private ApplicationDbContext _context;

        // GET: Customers
        public ActionResult Index()
        {
            var customers = GetCustomers();

            return View(customers);
        }

        public ActionResult Details(int id)
        {
            var customers = GetCustomers();
            var customer = customers.SingleOrDefault(c => c.Id == id);

            if (customer == null)
            {
                return HttpNotFound();
            }

            return View(customer);
        }


        private IEnumerable<Customer> GetCustomers()
        {
        return new List<Customer>() {
                new Customer() { Id = 1, Name = "Allen Smith" },
                new Customer() { Id = 2, Name = "John Paul" }
            };

        }
    }
}

VidlyMVC5/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VidlyMVC5.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

VidlyMVC5/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VidlyMVC5.Models;
using VidlyMVC5.ViewModels;

namespace VidlyMVC5.Controllers
{
    public class MoviesController : Controller
    {
        // GET: Movies/Random
        public ActionResult Random()
        {
            var movie = new Movie() { Name = "Shrek!" };
            var customers = new List<Customer>
            {
                new Customer() { Name = "cust1"},
                new Customer() { Name = "cust2"}
            };

            var viewModel = new MovieCustomersViewModel() { Movie = movie, Customers = customers };
            return View(viewModel);
        }

        public ActionResult Index()
        {
            var movies = GetMovies();
            return View(movies);
        }

        private IEnumerable<VidlyMVC5.Models.Movie> GetMovies()
        {
            return new List<Movie>()
            {
                new Movie{ Id = 1, Name = "Shrek1!"},
                new Movie{ Id = 2, Name = "Gone with the Wind!"}
            };
        }

        
    }
}

VidlyMVC5/Views/Customers/Details.cshtml
@model VidlyMVC5.Models.Customer

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

@Model.Name

VidlyMVC5/Views/Customers/Index.cshtml
@model IEnumerable<VidlyMVC5.Models.Customer>


<H2>My Customers page</H2>

@if (!Model.Any())
{
    <text>No customers</text>
}
else
{
    <table class="table table-bordered table-hover">
        <thead><tr><td>Customer</td></tr></thead>
        <tbody>
            @foreach (var customer in Model)
            {
            <tr>
                <td>
                    @Html.ActionLink(customer.Name, "Details", "Customers", new { id = customer.Id }, null)
                </td>
            </tr>
            }
        </tbody>
    </table>
}

VidlyMVC5/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

VidlyMVC5/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

VidlyMVC5/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

VidlyMVC5/Views/Movies/Index.cshtml
@model IEnumerable<VidlyMVC5.Models.Movie>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>My Movies Page</h2>

<ul>
    @foreach (var movie in Model)
    {
            <li>
                @movie.Name
            </li>
    }
</ul>

VidlyMVC5/Views/Movies/Random.cshtml
@model VidlyMVC5.ViewModels.MovieCustomersViewModel

@{
    ViewBag.Title = "Random";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{ 
    var className = Model.Customers.Count > 0 ? "popular" : null;
}
<h2 class="@className">@Model.Movie.Name</h2>


@if (Model.Customers.Count == 0)
{
    <text>No one has rented this movie before</text>
}
else
{
    <ul>
        @foreach (var customer in Model.Customers)
        {
            <li>@customer.Name</li>
        }
    </ul>
}

VidlyMVC5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

VidlyMVC5/Views/Shared/_navBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Vidly", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>


        <div>
            <ul>
                @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                <li>@Html.ActionLink("Movies", "Index", "Movies")</li>

            </ul>
        </div>


        <!--
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                        <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                        <li>@Html.ActionLink("Movies", "Index", "Movies")</li>

                    </ul>
                </div>
        -->
    </div>
</div>